# Generated by Django 3.1 on 2021-01-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210125_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Roboczy'), ('published', 'Opublikowany')], default='draft', max_length=10),
        ),
    ]
